version: '3.8'
services:
  ui:
    image: 494234474945.dkr.ecr.us-east-2.amazonaws.com/cicd-jenkins-docker:latest
    build:
      context: ./ui
      dockerfile: Dockerfile
    ports:
      - "3000:3000"

  api:
    image: 494234474945.dkr.ecr.us-east-2.amazonaws.com/cicd-jenkins-docker:latest
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - mongo

  mongo:
    image: mongo
    ports:
      - "27017:27017"
